### ISSUE TITLE
Password Encoding / Decoding

### ISSUE THREAD

**Issue by winglian** [cloudtrax/docs#1]
In the password documentation at https://github.com/cloudtrax/docs/blob/master/captive_portal/authentication/http/Password_Decoding.md you indicate that the algorithm uses XOR Encryption which is supported correctly by your Python example, however the PHP example uses the OR (^) command. If I swap out the `^` for an `xor`, the contrived sample doesn't work properly. Is the example correct? Is the sample made simply to work with the example code, but non-functional? Thanks!

**Comment by jdberry** [comment]
Hi @winglian. The ^ character in php is a bitwise XOR, which is what is desired in this case. "xor" in php is a logical XOR, which has a different meaning. See http://php.net/manual/en/language.operators.bitwise.php vs http://php.net/manual/en/language.operators.logical.php.

Is the function working for you as long as you don't make this (incorrect) change to the code?

**Comment by winglian** [comment]
Thanks for clarifying!
