### ISSUE TITLE
Custom splash page with https:// url are supported??

### ISSUE THREAD

**Issue by StarStep** [cloudtrax/docs#3]
I have tried to set up the:
 Splash page authentication type > URL to an HTTPS url as result im not able to use captive portal anymore after if i change it back to http...

**Comment by jdberry** [comment]
I want to make sure I understand your question. But first let me say:

* HTTP Authentication (authentication via a custom page/script) will likely work only with http. The access points have a limited number of SSL root certificates installed. Unless you manually install additional roots into the access points, which requires a custom.sh script, the Access Points will likely not be able to make a secure SSL connection, and the external http authentication will fail. So in most cases HTTP authentication should be done via an http script.
* This same issue does not affect external splash pages, as the Access Point does not address them directly: they are invoke only via redirect through the client browser. So external splash pages (captive portal pages), not authentication, should completely support https.

There should be no issue in switching your http authentication from http -> https -> http.
