### ISSUE TITLE
Response of server in HTTP Authentication API

### ISSUE THREAD

**Issue by arturmamedov** [cloudtrax/docs#7]
Hi, i can't configure my server for HTTP authentication.

I trying external splash page and internal one ... but both return me a failed authentication.
I configured my server API to generate the RA and to respond always ACCEPT, with the SECONDS and DOWNLOAD/UPLOAD but nothing.... auth ever fail!

in documentation there are two example of how to write the response body:

1 - https://github.com/cloudtrax/docs/tree/master/captive_portal/authentication/http#example-response
```
"CODE" "ACCEPT"
"RA" "1fb341292217da85e097f05f3c75b672"
"SECONDS" "3600"
"DOWNLOAD" "2000"
"UPLOAD" "800"
```
2 - https://github.com/cloudtrax/docs/tree/master/captive_portal/authentication/http#status-response-parameters
```
"[CODE]" "REJECT"
"[RA]" "7b40dfe92d85298b11c32d9a4e4d79c8"
"[BLOCKED_MSG]" "Unknown Client"
```
You see the brackets and apix ...
What of this is correct?
Or better, where i can find the "source" if it posible of the authentication mechanism of Access Point?

Many Thanks!

**Comment by ch3fk0ch** [comment]
Please contact support@cloudtrax.com or submit a request from https://help.cloudtrax.com. Thanks.
