### ISSUE TITLE
Example output for "outages" in node history

### ISSUE THREAD

**Issue by direvus** [cloudtrax/docs#8]
The section describing `/history/network/<network-id>/nodes` mentions "outages", but there is no indication in the example response of how the "outages" content would be structured.

It's also not clear what units are being used for the "speed" under "metrics".

**Comment by ch3fk0ch** [comment]
Hi direvus, thanks for the hint. I fixed the documentation. Does this answer all your questions?
https://github.com/cloudtrax/docs/blob/master/api/history.md#nodes

Thanks, Andreas

**Comment by ch3fk0ch** [comment]
Please contact support@cloudtrax.com or submit a request from https://help.cloudtrax.com in case there are more questions. Thanks.
