### ISSUE TITLE
Access to layer 7 "Applications" usage from API

### ISSUE THREAD

**Issue by aferrara** [cloudtrax/docs#9]
In the CloudTrax "Network Overview" you can see a breakdown of the network utilisation by application type. I can't see a way to collect this data from the API. Could you please clarify if this is possible.

**Comment by ch3fk0ch** [comment]
Hi, 

https://github.com/cloudtrax/docs/blob/master/api/history.md#network

In the json you see the timeslot (every 5 minute) and the reported traffic per ssid. The traffic type is the key of the json. Does this answer your question?

**Comment by ch3fk0ch** [comment]
Please contact support@cloudtrax.com or submit a request from https://help.cloudtrax.com in case there are more questions. Thanks.
